version: '3'
services:
  voter-service:
    build: .
    environment:
      - SPRING_PROFILE=docker-production
      - MONGODB_HOST=mongodb
  nginx:
    build: ./nginx
    ports: 
      - 8080:80 
  mongodb:
    image: mongo
    
