version: '3'
services:
  voter-service:
    build: .
    ports:
      - 8099:8099
    environment:
      - SPRING_PROFILE=docker-production
      - MONGODB_HOST=mongodb
  mongodb:
    image: mongo
    
