version: '2.4'
services:
  voter-service:
    build: .
    environment:
      - SPRING_PROFILE=docker-production
      - MONGODB_HOST=mongodb
    depends_on: 
      - mongodb
  nginx:
    build: ./nginx
    ports: 
      - 8080:80
    depends_on: 
      - voter-service
  mongodb:
    image: mongo:3.4
